#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${OPENWEBUI_DB_USER}') THEN
    CREATE ROLE ${OPENWEBUI_DB_USER} LOGIN PASSWORD '${OPENWEBUI_DB_PASSWORD}';
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${OPENWEBUI_DB_NAME}') THEN
    CREATE DATABASE ${OPENWEBUI_DB_NAME} OWNER ${OPENWEBUI_DB_USER};
  END IF;
END
$$;
SQL
